// <auto-generated />
namespace Garage2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class datetimenow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetimenow));
        
        string IMigrationMetadata.Id
        {
            get { return "201805250823001_date-time-now"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
